#Audio Settings Configuration: 0
#ACPWorkbench Version: 2.44.2
#Communication Port: USB[0] :mvsilicon B1 usb audio
#Created: 2026-03-18T00:38:54

[0x00-Firmware_Version]
firmware_type = 48
firmware_version = 0.5.2
effect_version = 2.43.2

[0x01-System_Control]
system_mode = 0
system_reset = 0
system_sample_rate_enable = 256
system_sample_rate = 8
system_mclk_source_enable = 1
system_mclk_source = 0
system_recover_enable = 0

#PGA0
[0x03-PGA0]
line1_left_enable = 0
line1_right_enable = 0
line2_left_enable = 0
line2_right_enable = 0
line4_left_enable = 0
line4_right_enable = 0
line5_left_enable = 0
line5_right_enable = 0
line1_left_gain = 63
line1_right_gain = 63
line2_left_gain = 63
line2_right_gain = 63
line4_5_left_gain = 63
line4_5_right_gain = 63
reserved = 63
reserved = 63
Diff_input_enable = 0
Diff_left_gain = 0
Diff_right_gain = 0
Line1_left_right_pins = 3
Line2_left_right_pins = 3
Line4_left_right_pins = 3
Line5_left_right_pins = 3

#ADC0
[0x04-ADC0]
enable = 0
mute = 0
left_volume = 4096
right_volume = 4096
sample_rate = 8
LR_swap = 0
hpc = 0
fade_time = 5
mclk_source = 0
dc_blocker = 1

#PGA1
[0x06-PGA1]
line3_left_mic1_enable = 0
line3_right_mic2_enable = 0
line3_left_mic1_gain = 31
line3_left_mic1_gain_boost = 0
line3_right_mic2_gain = 31
line3_right_mic2_gain_boost = 0
mic_line_sel = 0
line3_left_mic1_pin = 1
line3_right_mic2_pin = 1

#ADC1
[0x07-ADC1]
enable = 0
mute = 0
left_volume = 4096
right_volume = 4096
sample_rate = 8
LR_swap = 0
hpc = 0
fade_time = 5
mclk_source = 0
dc_blocker = 1

#AGC1
[0x08-AGC1]
mode = 0
max_level = 0
target_level = 0
max_gain = 0
min_gain = 0
gain_offset = 0
frame_time = 10
hold_time = 10
attack_time = 10
decay_time = 10
noise_gate_enable = 0
noise_gate_threshold = 5
noise_gate_mode = 0
noise_gate_hold_time = 0

#DAC0
[0x09-DAC0]
enable = 3
sample_rate = 8
mute = 0
left_volume = 3072
right_volume = 4543
dither = 1
scramble = 0
mode = 0
pause = 0
sample_edge_mode = 0
SCF_mute = 0
fade_time = 5
zero_num = 0
mclk_source = 0

#DAC1
[0x0a-DAC1]
enable = 1
sample_rate = 8
mute = 0
left_volume = 4096
right_volume = 4096
dither = 0
scramble = 0
mode = 0
pause = 0
sample_edge_mode = 0
SCF_mute = 0
fade_time = 5
zero_num = 0
mclk_source = 0

#I2S0
[0x0b-I2S0]
tx_enable = 0
rx_enable = 0
sample_rate = 0
mclk_source = 0
master_slave = 0
word_length = 0
stereo_mono = 0
fade_time = 0
data_format = 0
bclk_invert = 0
lrclk_invert = 0

#I2S1
[0x0c-I2S1]
tx_enable = 0
rx_enable = 0
sample_rate = 0
mclk_source = 0
master_slave = 0
word_length = 0
stereo_mono = 0
fade_time = 0
data_format = 0
bclk_invert = 0
lrclk_invert = 0

#SPDIF
[0x0d-SPDIF]
enable = 0
sample_rate = 0
channel_mode = 0
io_mode = 0
lock_status = 0

[0x80-Effect_List]
list = 15,15,5,11,4,41,13,23,12,25,28,4,4,101,4,2,15,4,4,20,24,13,23,4,4,101,4,2,15
name_effect1 = 1:BT Play Gain
name_effect2 = 1:USB Device Gain
name_effect3 = 2:Music Noise Suppressor
name_effect4 = 2:Music Silence Detector
name_effect5 = 2:Music Preamp EQ
name_effect6 = 3:DAC0 Compander
name_effect7 = 3:DAC0 VB
name_effect8 = 3:DAC0 VB Classic
name_effect9 = 3:DAC0 3D
name_effect10 = 3:DAC0 Exciter
name_effect11 = 3:DAC0 Stereo Widener
name_effect12 = 3:DAC0 DynamicEQLP
name_effect13 = 3:DAC0 DynamicEQHP
name_effect14 = 3:DAC0 Dynamic EQ
name_effect15 = 3:DAC0 EQ DSP
name_effect16 = 3:DAC0 DRC
name_effect17 = 3:DAC0 GAIN_OUT
name_effect18 = 4:DAC0 L EQ DSP
name_effect19 = 4:DAC0 R EQ DSP
name_effect20 = 5:DACX Phase Control
name_effect21 = 5:DACX Phase Delay
name_effect22 = 5:DACX VB
name_effect23 = 5:DACX VB Classic
name_effect24 = 5:DACX DynamicEQLP
name_effect25 = 5:DACX DynamicEQHP
name_effect26 = 5:DACX Dynamic EQ
name_effect27 = 5:DACX EQ DSP
name_effect28 = 5:DACX DRC
name_effect29 = 5:DACX GAIN_OUT

#1:BT Play Gain
[0x81-Gain_Control]
enable = 0
mute = 0
gain = 3002

#1:USB Device Gain
[0x82-Gain_Control]
enable = 1
mute = 0
gain = 4096

#2:Music Noise Suppressor
[0x83-Noise_Suppressor_Expander]
enable = 0
threshold = -4500
ratio = 3
attack = 2
release = 100

#2:Music Silence Detector
[0x84-SilenceDetector]
enable = 0
amplitude = 0

#2:Music Preamp EQ
[0x85-EQ]
enable = 1
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 60
filter1_Q = 512
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 512
filter2_gain = 0
filter3_enable = 1
filter3_type = 2
filter3_f0 = 10000
filter3_Q = 512
filter3_gain = 0
filter4_enable = 0
filter4_type = 0
filter4_f0 = 0
filter4_Q = 0
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#3:DAC0 Compander
[0x86-Compander]
Enable = 0
Threshold = 0
Ratio below = 100
Ratio above = 100
Attack Time = 5
Release Time = 100
Pregain = 0

#3:DAC0 VB
[0x87-MVBass]
enable = 1
cutoff_frequency = 55
intensity = 12
enhanced = 1

#3:DAC0 VB Classic
[0x88-MVBass_Classic]
enable = 0
cutoff_frequency = 100
intensity = 35

#3:DAC0 3D
[0x89-MV3D]
enable = 1
intensity = 50

#3:DAC0 Exciter
[0x8a-Harmonic_Exciter]
enable = 0
cutoff_frequency = 1000
dry = 80
wet = 80

#3:DAC0 Stereo Widener
[0x8b-Stereo_Widener]
enable = 0
shaping = 0

#3:DAC0 DynamicEQLP
[0x8c-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#3:DAC0 DynamicEQHP
[0x8d-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#3:DAC0 Dynamic EQ
[0x8e-User-defined_Effect]
enable = 0
Low_threshold = -3000
Normal_threshold = -1500
Hight_threshold = -1000
Attack = 100
Release = 1000

#3:DAC0 EQ DSP
[0x8f-EQ]
enable = 0
pregain = -26
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 0
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 1000
filter5_Q = 724
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 1000
filter6_Q = 724
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 1000
filter7_Q = 724
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 1000
filter8_Q = 724
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 1000
filter9_Q = 724
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 1000
filter10_Q = 724
filter10_gain = 0

#3:DAC0 DRC
[0x90-DRC]
enable = 0
mode = 0
type = 1
ql = 724
qh = 724
fc1 = 300
fc2 = 2000
threshold1 = 0
threshold2 = 0
threshold3 = 0
threshold4 = -5142
ratio1 = 100
ratio2 = 100
ratio3 = 100
ratio4 = 100
attack1 = 100
attack2 = 100
attack3 = 100
attack4 = 100
release1 = 1
release2 = 1
release3 = 1
release4 = 1
pregain1 = 4096
pregain2 = 4096
pregain3 = 4096
pregain4 = 4096

#3:DAC0 GAIN_OUT
[0x91-Gain_Control]
enable = 0
mute = 0
gain = 3002

#4:DAC0 L EQ DSP
[0x92-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#4:DAC0 R EQ DSP
[0x93-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#5:DACX Phase Control
[0x94-Phase_Control]
enable = 0
phase_difference = 0

#5:DACX Phase Delay
[0x95-PCM_Delay]
enable = 0
delay = 40
max_delay = 50
high_quality_enable = 1

#5:DACX VB
[0x96-MVBass]
enable = 0
cutoff_frequency = 100
intensity = 35
enhanced = 1

#5:DACX VB Classic
[0x97-MVBass_Classic]
enable = 0
cutoff_frequency = 100
intensity = 35

#5:DACX DynamicEQLP
[0x98-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#5:DACX DynamicEQHP
[0x99-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#5:DACX Dynamic EQ
[0x9a-User-defined_Effect]
enable = 0
Low_threshold = -3000
Normal_threshold = -1500
Hight_threshold = -1000
Attack = 100
Release = 1000

#5:DACX EQ DSP
[0x9b-EQ]
enable = 0
pregain = 0
calculation_type = 0
filter1_enable = 1
filter1_type = 0
filter1_f0 = 100
filter1_Q = 724
filter1_gain = 0
filter2_enable = 1
filter2_type = 0
filter2_f0 = 1000
filter2_Q = 724
filter2_gain = 0
filter3_enable = 1
filter3_type = 0
filter3_f0 = 5000
filter3_Q = 724
filter3_gain = 0
filter4_enable = 1
filter4_type = 0
filter4_f0 = 10000
filter4_Q = 724
filter4_gain = 0
filter5_enable = 0
filter5_type = 0
filter5_f0 = 0
filter5_Q = 0
filter5_gain = 0
filter6_enable = 0
filter6_type = 0
filter6_f0 = 0
filter6_Q = 0
filter6_gain = 0
filter7_enable = 0
filter7_type = 0
filter7_f0 = 0
filter7_Q = 0
filter7_gain = 0
filter8_enable = 0
filter8_type = 0
filter8_f0 = 0
filter8_Q = 0
filter8_gain = 0
filter9_enable = 0
filter9_type = 0
filter9_f0 = 0
filter9_Q = 0
filter9_gain = 0
filter10_enable = 0
filter10_type = 0
filter10_f0 = 0
filter10_Q = 0
filter10_gain = 0

#5:DACX DRC
[0x9c-DRC]
enable = 0
mode = 0
type = 1
ql = 724
qh = 724
fc1 = 300
fc2 = 2000
threshold1 = 0
threshold2 = 0
threshold3 = 0
threshold4 = -5142
ratio1 = 100
ratio2 = 100
ratio3 = 100
ratio4 = 100
attack1 = 100
attack2 = 100
attack3 = 100
attack4 = 100
release1 = 1
release2 = 1
release3 = 1
release4 = 1
pregain1 = 4096
pregain2 = 4096
pregain3 = 4096
pregain4 = 4096

#5:DACX GAIN_OUT
[0x9d-Gain_Control]
enable = 0
mute = 0
gain = 3002

[0xfc-User_Tag]
len = 13
data = 50,58,77,117,115,105,99,95,70,76,65,83,72

